<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="student_curd.aspx.cs" Inherits="curd_operation.student_curd" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Student CRUD</title>
</head>
<body>
    <form id="form1" runat="server">
        <table>

            <tr>
                <td>
                    <asp:Label ID="lblEnrollment_No" runat="server" Text="Enter your Enrollment No here:"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtEnrollment_No" runat="server"></asp:TextBox>
                   
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="lblStudent_Name" runat="server" Text="Enter your Student Name here:"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtStudent_Name" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="lblSemester" runat="server" Text="Enter Semester here:"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtSemester" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="lblSPI" runat="server" Text="Enter your SPI here:"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtSPI" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="lblCPI" runat="server" Text="Enter your CPI here:"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtCPI" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Button ID="btnAdd" runat="server" Text="Add" OnClick="btnAdd_Click" />
                </td>
            </tr>

            <tr>
                <td colspan="2">
                   <asp:GridView ID="grdData" runat="server" DataKeyNames="Stu_id" 
                       OnRowEditing="grdData_RowEditing1" OnRowCancelingEdit="grdData_RowCancelingEdit1"
                       PageSize="3" AllowPaging="true" OnRowDeleting="grdData_RowDeleting1" 
                       OnRowUpdating="grdData_RowUpdating1" AutoGenerateDeleteButton="true" 
                       AutoGenerateEditButton="true" EmptyDataText="Please Enter Data" 
                       OnPageIndexChanging="grdData_PageIndexChanging1" AutoGenerateColumns="false"> 

                 

                    <Columns>

                        <asp:BoundField DataField="Stu_id" HeaderText="Stu_id" Visible="false" />

                        <asp:TemplateField HeaderText="Enrollment No">
                            <itemtemplate>
                                <asp:Label ID="l_lblEnrollment_No" runat="server" Text='<%#Eval("Enrollment_No")%>'></asp:Label>
                            </itemtemplate>
                            <edititemtemplate>
                                <asp:TextBox ID="t_txtEnrollment_No" runat="server" Text='<%#Eval("Enrollment_No")%>'></asp:TextBox>
                            </edititemtemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Student Name">
                            <itemtemplate>
                                <asp:Label ID="l_lblStudent_Name" runat="server" Text='<%#Eval("Student_Name")%>'></asp:Label>
                            </itemtemplate>
                            <edititemtemplate>
                                <asp:TextBox ID="t_txtStudent_Name" runat="server" Text='<%#Eval("Student_Name")%>'></asp:TextBox>
                            </edititemtemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Semester">
                            <itemtemplate>
                                <asp:Label ID="l_lblSemester" runat="server" Text='<%#Eval("Semester")%>'></asp:Label>
                            </itemtemplate>
                            <edititemtemplate>
                                <asp:TextBox ID="t_txtSemester" runat="server" Text='<%#Eval("Semester")%>'></asp:TextBox>
                            </edititemtemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="SPI">
                            <itemtemplate>
                                <asp:Label ID="l_lblSPI" runat="server" Text='<%#Eval("SPI")%>'></asp:Label>
                            </itemtemplate>
                            <edititemtemplate>
                                <asp:TextBox ID="t_txtSPI" runat="server" Text='<%#Eval("SPI")%>'></asp:TextBox>
                            </edititemtemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="CPI">
                            <itemtemplate>
                                <asp:Label ID="l_lblCPI" runat="server" Text='<%#Eval("CPI")%>'></asp:Label>
                            </itemtemplate>
                            <edititemtemplate>
                                <asp:TextBox ID="t_txtCPI" runat="server" Text='<%#Eval("CPI")%>'></asp:TextBox>
                            </edititemtemplate>
                        </asp:TemplateField>

                    </Columns>
                    </asp:GridView>
                </td>
            </tr>
        </table>
    </form>
</body>
</html>
